### ISSUE TITLE
Bazel extension clobbers F# build script language detection.

### ISSUE THREAD

**Issue by baronfel** [devoncarew/bazel-code#11]
Hi,

In the F# community we often use a build dsl called FAKE, which uses normal F# language scripts (*.fsx files) to run the build.  The convention is to call these files "build.fsx", which unfortunately conflicts with the `filenamePatterns` that are defined in this project [here](https://github.com/devoncarew/bazel-code/blob/master/package.json#L34).  Is there another way to define this pattern that doesn't conflict in this way?

**Comment by devoncarew** [comment]
I believe the bazel ones are case sensitive and upper case. Perhaps the regex could be updated to be case sensitive?

**Comment by devoncarew** [comment]
Likely fixed by https://github.com/devoncarew/bazel-code/pull/13.
