### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by Helcaraxan** [devoncarew/bazel-code#15]
Would it be possible to do a new release now that #13 has been merged a while ago? Having the update make it into the editor via the plugin manager would be great. 🙂

**Comment by devoncarew** [comment]
Updated now :)

https://marketplace.visualstudio.com/items?itemName=DevonDCarew.bazel-code

Sorry for the delay...

**Comment by Helcaraxan** [comment]
Thank you @devoncarew !
