### ISSUE TITLE
Add formatting using buildifier

### ISSUE THREAD

**Issue by tbroyer** [devoncarew/bazel-code#2]
This extension would be even better if it could leverage [`buildifier`](https://github.com/bazelbuild/buildifier) to format the `WORKSPACE` and `BUILD` files. I'm not a great Bazel user (just toying with it from time to time) but I'd happily use that with `editor.formatOnSave`.
Maybe it could start with using it if available in the `$PATH`, then possibly (if Go is available) propose to install it with a `go get`.

**Comment by devoncarew** [comment]
Sounds great! I mostly wrote this to get bazel syntax highlighting, but am happy to take contributions.
