### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by laurentlb** [devoncarew/bazel-code#21]
Hi,

We have another VS Code plugin under active development (https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel, https://github.com/bazelbuild/vscode-bazel).

- Are there important features we should port to the other plugin?
- Can we mark this plugin as deprecated?

I'd like to make sure new users know which plugin to install and don't take this one by accident.

Thanks!
(cc @jin)

**Comment by devoncarew** [comment]
Circling back to this - this has now been done.
