### ISSUE TITLE
Formatting the document makes it's content out of date

### ISSUE THREAD

**Issue by cheshirekow** [devoncarew/bazel-code#22]
It seems that however this plugin is calling `buildifier` is conflicting with vscode's model of file changes. Whenever I format a file using the `Format Document` action, the file is changed on disk but the view in vscode remains the same. I am then unable to modify the file and save due to this:

![image](https://user-images.githubusercontent.com/1309820/74763769-3f7b2200-5235-11ea-9c78-361330d0ff8d.png)

**Comment by ivanmilov** [comment]
Agree with TS, have the same issue

**Comment by laurentlb** [comment]
I'd recommend you to try the other plugin, which is maintained:
https://github.com/bazelbuild/vscode-bazel
https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel

**Comment by cheshirekow** [comment]
Thanks @laurentlb. I didn't think that the bazelbuild extension did `buildifier` but it looks like it does in fact.

**Comment by devoncarew** [comment]
Closing this as we're deprecating this extension in favor of https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel.
