### ISSUE TITLE
Provide syntax highlighting for BUILD.xxxxxx

### ISSUE THREAD

**Issue by prestonvanloon** [devoncarew/bazel-code#4]
When using `new_http_archive` or `new_git_repository` or `new_local_repository`, it is common to name specific build files in the format of `BUILD.name_of_module`

https://bazel.build/versions/master/docs/be/workspace.html#new_http_archive

Syntax highlighting for those type files would be helpful.

**Comment by devoncarew** [comment]
This could probably be addressed with a patch into https://github.com/devoncarew/bazel-code/blob/master/package.json#L27 ?

**Comment by prestonvanloon** [comment]
Yes. Maybe using filenamePatterns?

https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/editor/common/services/modeService.ts#L23
